name: repo_viewer
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  analyzer: ^5.1.0
  auto_route: ^5.0.1
  dartz: ^0.10.1
  dio: ^4.0.6
  flash: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^6.0.0
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^2.0.2
  oauth2: ^2.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true
